pipeline {
    agent {
        label 'agent-maven'
    }

    options {
        disableConcurrentBuilds()
        timeout(time: 20, unit: 'MINUTES')
    }

    environment {
        APP_NAME        = 'hello-world-api'
        APP_DIR         = 'app/hello-world-api'
        AWS_REGION      = 'ca-central-1'
        ECR_REGISTRY    = '123456789012.dkr.ecr.ca-central-1.amazonaws.com'
        ECR_REPOSITORY  = 'hello-world-api'
        IMAGE_BUILD_TAG = "${BUILD_NUMBER}"
        IMAGE_SHA_TAG   = "${GIT_COMMIT}".take(7)
        IMAGE_URI       = "${ECR_REGISTRY}/${ECR_REPOSITORY}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                script {
                    env.SHORT_COMMIT = sh(
                        script: "git rev-parse --short HEAD",
                        returnStdout: true
                    ).trim()
                }
            }
        }


        stage('Test') {
            steps {
                dir("${APP_DIR}") {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit allowEmptyResults: true, testResults: "${APP_DIR}/target/surefire-reports/*.xml"
                }
            }
        }
    }

}