controller:
  admin:
    username: admin
    password: admin123

  serviceType: ClusterIP

  # Do not run builds on the controller
  numExecutors: 0

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - pipeline-stage-view
    - job-dsl
    - aws-credentials
    - junit
    - docker-workflow
    - amazon-ecr
    - timestamper

  initializeOnce: true

  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Jenkins configured via Helm and JCasC"

      jobs: |
        jobs:
          - script: |
              folder('applications') {
                description('Application build jobs')
              }

      pipeline-job: |
        jobs:
          - script: |
              pipelineJob('ci-pipeline-hello-world-api') {
                description('CI Pipeline job for project hello-world-api')

                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/simonangel-fong/Jenkins_Demo_SpringBoot_ECR.git')
                        }
                        branches('*')
                      }
                    }
                    scriptPath('cicd/ci/Jenkinsfile')
                  }
                }
              }

persistence:
  enabled: true
  size: 2Gi

agent:
  enabled: true

  # optional tuning
  maxRequestsPerHostStr: "32"
  retentionTimeout: "5"
  waitForPodSec: "120"

  podTemplates:
    maven: |
      - name: maven
        label: agent-maven
        serviceAccount: jenkins
        containers:
          - name: maven
            image: maven:3.9.14-eclipse-temurin-21-alpine
            command: "/bin/sh -c"
            args: "cat"
            ttyEnabled: true
            resourceRequestCpu: "500m"
            resourceRequestMemory: "512Mi"
            resourceLimitCpu: "1"
            resourceLimitMemory: "1Gi"

          - name: dind
            image: docker:27-dind
            command: "dockerd-entrypoint.sh"
            args: "--host=unix:///var/run/docker.sock"
            ttyEnabled: true
            privileged: true
            resourceRequestCpu: "500m"
            resourceRequestMemory: "512Mi"
            resourceLimitCpu: "1"
            resourceLimitMemory: "1Gi"